{
    "name": "Edu Skill",
    "summary": """Provide online Education""",
    "author": "Odoo Community Association (OCA)",
    "website": "https://github.com/OCAoca/",
    "category": "Uncategorized",
    "version": "15.0.1.0.0",
    "depends": ["base", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "views/teacher_details_views.xml",
        "views/category_details_views.xml",
        "views/course_view.xml",
        "views/user_details.xml",
        "views/category_details_views.xml",
        "views/video_details_views.xml",
        "views/quiz_details.xml",
        "views/course_order.xml",
        "views/quiz_result_detail.xml",
        "views/course_order_item.xml",
        "views/review_rating_detail.xml",
        "views/res_config_settings_views.xml",
        "views/teacher_menu_views.xml",
    ],
    "application": True,
    "license": "LGPL-3",
}
